branch-defaults:
  master:
    environment: pop-consultation-staging
environment-defaults:
  pop-consultation:
    branch: null
    repository: null
  pop-consultation-staging:
    branch: null
    repository: null
global:
  application_name: pop_consultation
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-3::platform/Node.js 14 running on
    64bit Amazon Linux 2/5.4.9
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
