branch-defaults:
  develop:
    environment: pop-consultation-staging
  master:
    environment: pop-consultation
environment-defaults:
  pop-production:
    branch: null
    repository: null
  production:
    branch: null
    repository: null
global:
  application_name: pop_consultation
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:eu-west-3::platform/Node.js running on
    64bit Amazon Linux/4.5.0
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
